### ISSUE TITLE
Upstream Tyrano could work with the latest nwjs

### ISSUE THREAD

**Issue by es20490446e** [Chion82/teaching-feeling-web#2]
I'm porting Teaching Feeling and Tyrano to Linux, and I have noticed something interesting. The official build of the game only works with an old version of nwjs, while the web version works with the latest one.

Any idea why is that?

**Comment by kinglyl** [comment]
**UPDATE?**

**Comment by es20490446e** [comment]
It seems that the cause is that all the components are arranged with very specific versions of node.js modules. For the moment I don't see a solution other than to bundle the game with the right versions.

That said I have published a [patch](https://gitlab.com/es20490446e/teaching-feeling-v2-linux) for making the game compatible with Linux, and requested to [merge](https://github.com/ShikemokuMK/tyranoscript/pull/72) these changes to the Tyrano engine itself.
